name: OpenWrt Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential git terminal-colors gawk gettext libncurses5-dev libssl-dev python3 unzip zlib1g-dev
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Clone source code
        run: |
          git clone https://github.com/immortalwrt/immortalwrt -b openwrt-24.10 openwrt

      - name: Load custom feeds
        run: |
          cd openwrt
          echo 'src-git linkease https://github.com/linkease/istore;main' >> feeds.conf.default
          echo 'src-git nas https://github.com/linkease/nas-packages.git;master' >> feeds.conf.default
          echo 'src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main' >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0

      - name: Download package
        run: |
          cd openwrt
          make defconfig
          make download -j8

      - name: Compile the firmware
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware
          path: openwrt/bin/targets/
